stages:
  - build
  - coverage

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

pages:
  stage: coverage
  image: xd009642/tarpaulin
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq lcov
  script:
    - cargo tarpaulin -o Lcov --exclude-files main.rs repl.rs
    - genhtml lcov.info -o public
  artifacts:
    paths:
      - public
    expire_in: 30 days
