[package]
name = "pile"
version = "0.1.0"
authors = ["0x28"]
edition = "2018"

[dependencies]
atty = "0.2.14"
clap = "2.33.3"
dirs = "3.0.1"
rustyline = "6.3.0"

[dev-dependencies]
proptest = "0.10.1"
